[package]
name = "tabctl"
version = "0.6.0-alpha.14"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = ["std"] }
dirs = "5"
dunce = "1"
serde_json = "1"
sha2 = "0.10"
zip = { version = "2", default-features = false, features = ["deflate"] }
tabctl-host = { path = "../host" }
tabctl-shared = { path = "../shared" }
tabctl-graphql = { path = "../graphql" }

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
