/**
 * Wrapper health checks — parse, validate, and repair profile wrapper scripts.
 *
 * Wrappers are generated by `tabctl setup` and launch the native messaging host.
 * They hardcode absolute paths to Node and the host bundle, which can break when
 * Node is upgraded (e.g., via mise/nvm). This module detects and fixes stale paths.
 */

import fs from "node:fs";
import path from "node:path";

export type WrapperInfo = {
  nodePath: string;
  hostPath: string;
  profileName: string | null;
  hostImplementation: "node" | "rust";
};

export type WrapperCheck = {
  ok: boolean;
  wrapperPath: string;
  info: WrapperInfo | null;
  issues: string[];
};

// Unix: exec "nodePath" "hostPath"
const SH_EXEC_RE = /^exec\s+"([^"]+)"\s+"([^"]+)"$/m;
// Unix rust mode: exec "hostPath"
const SH_EXEC_SINGLE_RE = /^exec\s+"([^"]+)"(?:\s+"\$@")?$/m;
// Unix: export TABCTL_PROFILE="name"
const SH_PROFILE_RE = /^export\s+TABCTL_PROFILE="([^"]+)"$/m;
// Unix: export TABCTL_HOST_IMPL="rust|node"
const SH_HOST_IMPL_RE = /^export\s+TABCTL_HOST_IMPL="([^"]+)"$/m;

// Windows .cmd: "nodePath" "hostPath" %*
const CMD_EXEC_RE = /^"([^"]+)"\s+"([^"]+)"\s+%\*$/m;
// Windows .cmd rust mode: "hostPath" %*
const CMD_EXEC_SINGLE_RE = /^"([^"]+)"\s+%\*$/m;
// Windows .cmd: set TABCTL_PROFILE=name
const CMD_PROFILE_RE = /^set\s+TABCTL_PROFILE=(.+)$/m;
// Windows .cmd: set TABCTL_HOST_IMPL=rust|node
const CMD_HOST_IMPL_RE = /^set\s+TABCTL_HOST_IMPL=(.+)$/m;

// Windows .cfg (Go launcher): line 1 = node/runtime, line 2 = host/arg, optional TABCTL_PROFILE=name
const CFG_PROFILE_RE = /^TABCTL_PROFILE=(.+)$/m;
// Windows .cfg: TABCTL_HOST_IMPL=rust|node
const CFG_HOST_IMPL_RE = /^TABCTL_HOST_IMPL=(.+)$/m;

function normalizeHostImplementation(value: string | undefined): "node" | "rust" {
  const normalized = String(value || "").trim().toLowerCase();
  return normalized === "rust" ? "rust" : "node";
}

/**
 * Parse a wrapper script to extract Node path, host path, and profile name.
 * Supports .sh (Unix), .cmd (Windows fallback), and .cfg (Go launcher) formats.
 */
export function parseWrapper(wrapperPath: string): WrapperInfo | null {
  try {
    const ext = path.extname(wrapperPath).toLowerCase();

    // .cfg: Go launcher config (host-launcher.cfg next to .exe)
    if (ext === ".cfg") {
      const content = fs.readFileSync(wrapperPath, "utf-8");
      const lines = content.split(/\r?\n/).filter(l => l.trim());
      if (lines.length < 2) return null;
      const profileMatch = content.match(CFG_PROFILE_RE);
      const hostImplMatch = content.match(CFG_HOST_IMPL_RE);
      return {
        nodePath: lines[0].trim(),
        hostPath: lines[1].trim(),
        profileName: profileMatch ? profileMatch[1].trim() : null,
        hostImplementation: normalizeHostImplementation(hostImplMatch ? hostImplMatch[1] : undefined),
      };
    }

    // .exe: look for host-launcher.cfg in the same directory
    if (ext === ".exe") {
      const cfgPath = path.join(path.dirname(wrapperPath), "host-launcher.cfg");
      if (fs.existsSync(cfgPath)) {
        return parseWrapper(cfgPath);
      }
      return null;
    }

    const content = fs.readFileSync(wrapperPath, "utf-8");

    // .cmd: Windows batch
    if (ext === ".cmd") {
      const hostImplMatch = content.match(CMD_HOST_IMPL_RE);
      const hostImplementation = normalizeHostImplementation(hostImplMatch ? hostImplMatch[1] : undefined);
      const execMatch = content.match(CMD_EXEC_RE);
      if (!execMatch) {
        const singleExecMatch = content.match(CMD_EXEC_SINGLE_RE);
        if (!(singleExecMatch && hostImplementation === "rust")) return null;
        const profileMatch = content.match(CMD_PROFILE_RE);
        return {
          nodePath: singleExecMatch[1],
          hostPath: singleExecMatch[1],
          profileName: profileMatch ? profileMatch[1].trim() : null,
          hostImplementation,
        };
      }
      const profileMatch = content.match(CMD_PROFILE_RE);
      return {
        nodePath: execMatch[1],
        hostPath: execMatch[2],
        profileName: profileMatch ? profileMatch[1].trim() : null,
        hostImplementation,
      };
    }

    // .sh or extensionless: Unix shell
    const hostImplMatch = content.match(SH_HOST_IMPL_RE);
    const hostImplementation = normalizeHostImplementation(hostImplMatch ? hostImplMatch[1] : undefined);
    const execMatch = content.match(SH_EXEC_RE);
    if (!execMatch) {
      const singleExecMatch = content.match(SH_EXEC_SINGLE_RE);
      if (!(singleExecMatch && hostImplementation === "rust")) return null;
      const profileMatch = content.match(SH_PROFILE_RE);
      return {
        nodePath: singleExecMatch[1],
        hostPath: singleExecMatch[1],
        profileName: profileMatch ? profileMatch[1] : null,
        hostImplementation,
      };
    }
    const profileMatch = content.match(SH_PROFILE_RE);
    return {
      nodePath: execMatch[1],
      hostPath: execMatch[2],
      profileName: profileMatch ? profileMatch[1] : null,
      hostImplementation,
    };
  } catch {
    return null;
  }
}

/**
 * Check wrapper health: parse it and verify all referenced paths exist.
 */
export function checkWrapper(wrapperPath: string): WrapperCheck {
  const issues: string[] = [];

  if (!fs.existsSync(wrapperPath)) {
    return { ok: false, wrapperPath, info: null, issues: [`Wrapper not found: ${wrapperPath}`] };
  }

  const info = parseWrapper(wrapperPath);
  if (!info) {
    return { ok: false, wrapperPath, info: null, issues: [`Could not parse wrapper: ${wrapperPath}`] };
  }

  const seenPaths = new Set<string>();
  if (!fs.existsSync(info.nodePath)) {
    issues.push(`Node path not found: ${info.nodePath}`);
    seenPaths.add(info.nodePath);
  }
  if (!fs.existsSync(info.hostPath) && !seenPaths.has(info.hostPath)) {
    issues.push(`Host path not found: ${info.hostPath}`);
  }

  return { ok: issues.length === 0, wrapperPath, info, issues };
}

/**
 * Resolve the wrapper path for a profile data directory.
 * Returns the path (may not exist yet).
 */
export function resolveWrapperPath(profileDataDir: string): string {
  if (process.platform === "win32") {
    const exePath = path.join(profileDataDir, "tabctl-host.exe");
    if (fs.existsSync(exePath)) return exePath;
    const cmdPath = path.join(profileDataDir, "tabctl-host.cmd");
    if (fs.existsSync(cmdPath)) return cmdPath;
    return exePath; // default to .exe
  }
  return path.join(profileDataDir, "tabctl-host.sh");
}

/**
 * Resolve the text-editable config path for a wrapper.
 * For .exe wrappers, this is the adjacent host-launcher.cfg.
 * For .sh/.cmd, it's the wrapper itself.
 */
export function resolveWrapperTextPath(wrapperPath: string): string {
  const ext = path.extname(wrapperPath).toLowerCase();
  if (ext === ".exe") {
    return path.join(path.dirname(wrapperPath), "host-launcher.cfg");
  }
  return wrapperPath;
}
