/**
 * Wrapper health checks — parse, validate, and repair profile wrapper scripts.
 *
 * Wrappers are generated by `tabctl setup` and launch the native messaging host.
 * They hardcode absolute paths to Node and the host bundle, which can break when
 * Node is upgraded (e.g., via mise/nvm). This module detects and fixes stale paths.
 */

import fs from "node:fs";
import path from "node:path";

export type WrapperInfo = {
  nodePath: string;
  hostPath: string;
  profileName: string | null;
};

export type WrapperCheck = {
  ok: boolean;
  wrapperPath: string;
  info: WrapperInfo | null;
  issues: string[];
};

// Unix: exec "nodePath" "hostPath"
const SH_EXEC_RE = /^exec\s+"([^"]+)"\s+"([^"]+)"$/m;
// Unix: export TABCTL_PROFILE="name"
const SH_PROFILE_RE = /^export\s+TABCTL_PROFILE="([^"]+)"$/m;

// Windows .cmd: "nodePath" "hostPath" %*
const CMD_EXEC_RE = /^"([^"]+)"\s+"([^"]+)"\s+%\*$/m;
// Windows .cmd: set TABCTL_PROFILE=name
const CMD_PROFILE_RE = /^set\s+TABCTL_PROFILE=(.+)$/m;

// Windows .cfg (Go launcher): line 1 = node, line 2 = host, optional TABCTL_PROFILE=name
const CFG_PROFILE_RE = /^TABCTL_PROFILE=(.+)$/m;

/**
 * Parse a wrapper script to extract Node path, host path, and profile name.
 * Supports .sh (Unix), .cmd (Windows fallback), and .cfg (Go launcher) formats.
 */
export function parseWrapper(wrapperPath: string): WrapperInfo | null {
  try {
    const ext = path.extname(wrapperPath).toLowerCase();

    // .cfg: Go launcher config (host-launcher.cfg next to .exe)
    if (ext === ".cfg") {
      const content = fs.readFileSync(wrapperPath, "utf-8");
      const lines = content.split(/\r?\n/).filter(l => l.trim());
      if (lines.length < 2) return null;
      const profileMatch = content.match(CFG_PROFILE_RE);
      return {
        nodePath: lines[0].trim(),
        hostPath: lines[1].trim(),
        profileName: profileMatch ? profileMatch[1].trim() : null,
      };
    }

    // .exe: look for host-launcher.cfg in the same directory
    if (ext === ".exe") {
      const cfgPath = path.join(path.dirname(wrapperPath), "host-launcher.cfg");
      if (fs.existsSync(cfgPath)) {
        return parseWrapper(cfgPath);
      }
      return null;
    }

    const content = fs.readFileSync(wrapperPath, "utf-8");

    // .cmd: Windows batch
    if (ext === ".cmd") {
      const execMatch = content.match(CMD_EXEC_RE);
      if (!execMatch) return null;
      const profileMatch = content.match(CMD_PROFILE_RE);
      return {
        nodePath: execMatch[1],
        hostPath: execMatch[2],
        profileName: profileMatch ? profileMatch[1].trim() : null,
      };
    }

    // .sh or extensionless: Unix shell
    const execMatch = content.match(SH_EXEC_RE);
    if (!execMatch) return null;
    const profileMatch = content.match(SH_PROFILE_RE);
    return {
      nodePath: execMatch[1],
      hostPath: execMatch[2],
      profileName: profileMatch ? profileMatch[1] : null,
    };
  } catch {
    return null;
  }
}

/**
 * Check wrapper health: parse it and verify all referenced paths exist.
 */
export function checkWrapper(wrapperPath: string): WrapperCheck {
  const issues: string[] = [];

  if (!fs.existsSync(wrapperPath)) {
    return { ok: false, wrapperPath, info: null, issues: [`Wrapper not found: ${wrapperPath}`] };
  }

  const info = parseWrapper(wrapperPath);
  if (!info) {
    return { ok: false, wrapperPath, info: null, issues: [`Could not parse wrapper: ${wrapperPath}`] };
  }

  if (!fs.existsSync(info.nodePath)) {
    issues.push(`Node path not found: ${info.nodePath}`);
  }
  if (!fs.existsSync(info.hostPath)) {
    issues.push(`Host path not found: ${info.hostPath}`);
  }

  return { ok: issues.length === 0, wrapperPath, info, issues };
}

/**
 * Resolve the wrapper path for a profile data directory.
 * Returns the path (may not exist yet).
 */
export function resolveWrapperPath(profileDataDir: string): string {
  if (process.platform === "win32") {
    const exePath = path.join(profileDataDir, "tabctl-host.exe");
    if (fs.existsSync(exePath)) return exePath;
    const cmdPath = path.join(profileDataDir, "tabctl-host.cmd");
    if (fs.existsSync(cmdPath)) return cmdPath;
    return exePath; // default to .exe
  }
  return path.join(profileDataDir, "tabctl-host.sh");
}
