#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);
const marker = process.env.NPX_CAPTURE_PATH || path.join(process.cwd(), "npx-args.json");

fs.writeFileSync(marker, JSON.stringify({ args }, null, 2), "utf8");
process.exit(0);
